version: "3.7"

services:

  backend:
    build: Backend/.
    restart: always
    ports:
      - "5000:5000"
    networks:
      - MyNetwork

  frontend:
    build: Frontend/.
    restart: always
    depends_on:
      - backend
    ports:
      - "4000:4000"
    networks:
      - MyNetwork

networks:

  MyNetwork:
    driver: bridge
